FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:jessie-run

ENV INITSYSTEM on

# Install XORG
RUN apt-get update && apt-get install --no-install-recommends xserver-xorg xserver-xorg-input-evdev

# To to able to start X from the terminal
RUN apt-get install --no-install-recommends xinit

# Install desktop environment
RUN apt-get install xfce4 xfce4-terminal

RUN apt-get clean

# Setting working directory
WORKDIR /usr/src/app

COPY . ./

CMD ["bash", "start.sh"]